### ISSUE TITLE
Bot gets stucked with MEGA links

### ISSUE THREAD

**Issue by Ciro235** [Amaimersion/yandex-disk-telegram-bot#16] opened 2021-12-14 20:10 UTC
# Bug Report

## Expected Behavior

Error message. Or mega link not supported 

## Actual Behavior

Loop where it keeps uploading the same text html file. 

It keeps uploadingName: mega.nz Type: development (text/html) Size: 2.7 KB (2,682 bytes) Public URL: https://yadi.sk/d/3eDm2gp1detZUg SHA-256: 353683146be0b4e48e83d4c4b6b3677e5baaa149ed533b61ba26040e123f80e4 MD5: fc518c5cd17994601144e6dece6fdc0e

**Comment by Ciro235** [comment] 2021-12-14 20:11
Btw. The bot is amazing😎

**Comment by Amaimersion** [comment] 2021-12-20 14:42
Hi! Sorry for waiting and thank you for nice words.

**Comment by Amaimersion** [comment] 2021-12-20 14:43
Actually, HTML file is a way by which MEGA links are supported. It is not me who parses and downloads from links. It is Yandex.Disk job. I'm just passing the links to Yandex.Disk and getting response, so I cannot and will not decide if provided link is supported or not. 

Yandex.Disk cannot download content of MEGA link, but it can download HTML page itself. So, it is how Yandex.Disk supports MEGA links. Perhaps there is some libs that provides support specially for MEGA, but at the moment I don't have a time to write or integrate them. Feel free to mention such lib or even better - create PR.

**Comment by Amaimersion** [comment] 2021-12-20 14:44
You can try to pass direct link to file from MEGA, not folder itself. This way Yandex.Disk will download the file.

**Comment by Amaimersion** [comment] 2021-12-20 14:45
I'm closing this because actually it is not a bug but expected poor support of different services. Feel free to reopen this in case of objections or ideas.

**Closed by Amaimersion** 2021-12-20 14:45 UTC
